//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcoa.Framework.Admin.GarService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GarService.IGarService")]
    public interface IGarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGarService/GetGarApplication", ReplyAction="http://tempuri.org/IGarService/GetGarApplicationResponse")]
        Alcoa.Framework.Common.Presentation.GarService.GarApplication GetGarApplication(string appCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGarServiceChannel : Alcoa.Framework.Admin.GarService.IGarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GarServiceClient : System.ServiceModel.ClientBase<Alcoa.Framework.Admin.GarService.IGarService>, Alcoa.Framework.Admin.GarService.IGarService {
        
        public GarServiceClient() {
        }
        
        public GarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Alcoa.Framework.Common.Presentation.GarService.GarApplication GetGarApplication(string appCode) {
            return base.Channel.GetGarApplication(appCode);
        }
    }
}
