//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcoa.Framework.Common.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alcoa.Framework.Common.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificateAppFolderAndName or CertificateSubjectName was not found..
        /// </summary>
        internal static string CertificateKeyNotFound {
            get {
                return ResourceManager.GetString("CertificateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate was not found or can&apos;t be loaded..
        /// </summary>
        internal static string CertificateLoadError {
            get {
                return ResourceManager.GetString("CertificateLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuerName configuration key was not found..
        /// </summary>
        internal static string IssuerNameKeyNotFound {
            get {
                return ResourceManager.GetString("IssuerNameKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Code.
        /// </summary>
        internal static string LabelAppCode {
            get {
                return ResourceManager.GetString("LabelAppCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name.
        /// </summary>
        internal static string LabelAppTitle {
            get {
                return ResourceManager.GetString("LabelAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string LabelAppVersion {
            get {
                return ResourceManager.GetString("LabelAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Line.
        /// </summary>
        internal static string LabelDirectLine {
            get {
                return ResourceManager.GetString("LabelDirectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string LabelExtensionLine {
            get {
                return ResourceManager.GetString("LabelExtensionLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}© - Alcoa App - Version {1}.
        /// </summary>
        internal static string LabelFooter {
            get {
                return ResourceManager.GetString("LabelFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup BPO.
        /// </summary>
        internal static string LabelGarBackupBPO {
            get {
                return ResourceManager.GetString("LabelGarBackupBPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Track Leader.
        /// </summary>
        internal static string LabelGarBackupLeader {
            get {
                return ResourceManager.GetString("LabelGarBackupLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPOs.
        /// </summary>
        internal static string LabelGarBPOsTitle {
            get {
                return ResourceManager.GetString("LabelGarBPOsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Track Leaders.
        /// </summary>
        internal static string LabelGarLeadersTitle {
            get {
                return ResourceManager.GetString("LabelGarLeadersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main BPO.
        /// </summary>
        internal static string LabelGarMainBPO {
            get {
                return ResourceManager.GetString("LabelGarMainBPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Track Leader.
        /// </summary>
        internal static string LabelGarMainLeader {
            get {
                return ResourceManager.GetString("LabelGarMainLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAR Information.
        /// </summary>
        internal static string LabelGarTitle {
            get {
                return ResourceManager.GetString("LabelGarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change User.
        /// </summary>
        internal static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LabelMenuAbout {
            get {
                return ResourceManager.GetString("LabelMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string LabelMenuHelp {
            get {
                return ResourceManager.GetString("LabelMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Apps.
        /// </summary>
        internal static string LabelMenuMyApps {
            get {
                return ResourceManager.GetString("LabelMenuMyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report an Issue.
        /// </summary>
        internal static string LabelMenuOpenTicket {
            get {
                return ResourceManager.GetString("LabelMenuOpenTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string LabelMessageTitle {
            get {
                return ResourceManager.GetString("LabelMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Desk Contact.
        /// </summary>
        internal static string LabelServiceDeskContact {
            get {
                return ResourceManager.GetString("LabelServiceDeskContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcoan Identification.
        /// </summary>
        internal static string LabelUserTitle {
            get {
                return ResourceManager.GetString("LabelUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 041-(35)-21019200.
        /// </summary>
        internal static string ServiceDeskDirectLine {
            get {
                return ResourceManager.GetString("ServiceDeskDirectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9200.
        /// </summary>
        internal static string ServiceDeskExtension {
            get {
                return ResourceManager.GetString("ServiceDeskExtension", resourceCulture);
            }
        }
    }
}
