//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alcoa.Framework.Connection.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alcoa.Framework.Connection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameworkAlcoaActiveDirectory.xml.
        /// </summary>
        internal static string ActiveDirectoryFileName {
            get {
                return ResourceManager.GetString("ActiveDirectoryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \FileRepository\.
        /// </summary>
        internal static string FileRepositoryFolderName {
            get {
                return ResourceManager.GetString("FileRepositoryFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameworkAlcoaInstance.xml.
        /// </summary>
        internal static string InstanceFileName {
            get {
                return ResourceManager.GetString("InstanceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory vault file was not found, check at VaultPath and VaultFolderToSearch.
        /// </summary>
        internal static string MsgActiveDirectoryVaultFileNotFound {
            get {
                return ResourceManager.GetString("MsgActiveDirectoryVaultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string not found for profile: {0}.
        /// </summary>
        internal static string MsgConnectionStringNotFoundForProfile {
            get {
                return ResourceManager.GetString("MsgConnectionStringNotFoundForProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context name can&apos;t be empty or null.
        /// </summary>
        internal static string MsgContextCantBeNull {
            get {
                return ResourceManager.GetString("MsgContextCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework vault file was not found, check at VaultPath and VaultFolderToSearch.
        /// </summary>
        internal static string MsgFrameworkVaultFileNotFound {
            get {
                return ResourceManager.GetString("MsgFrameworkVaultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance vault file was not found, check at VaultPath and VaultFolderToSearch.
        /// </summary>
        internal static string MsgInstanceVaultFileNotFound {
            get {
                return ResourceManager.GetString("MsgInstanceVaultFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0}, does not exist on database package/procedure.
        /// </summary>
        internal static string MsgParameterNotFound {
            get {
                return ResourceManager.GetString("MsgParameterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters differs from database package/procedure.
        /// </summary>
        internal static string MsgParameterNumberDiffers {
            get {
                return ResourceManager.GetString("MsgParameterNumberDiffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database profile not found: {0}.
        /// </summary>
        internal static string MsgProfileNotFound {
            get {
                return ResourceManager.GetString("MsgProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized access from environment {0} to the instance {1}.
        /// </summary>
        internal static string MsgUnauthorizedAccessToInstance {
            get {
                return ResourceManager.GetString("MsgUnauthorizedAccessToInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FrameworkAlcoaVault.xml.
        /// </summary>
        internal static string VaultFileName {
            get {
                return ResourceManager.GetString("VaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        internal static string VaultFolderToSearch {
            get {
                return ResourceManager.GetString("VaultFolderToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\.
        /// </summary>
        internal static string VaultPath {
            get {
                return ResourceManager.GetString("VaultPath", resourceCulture);
            }
        }
    }
}
